/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pablocompany.proyectono2lfp.frontend;

import com.pablocompany.proyectono2lfp.analizadorlexicorecursos.LectorEntradas;
import com.pablocompany.proyectono2lfp.backendswing.ColocarFondos;
import com.pablocompany.proyectono2lfp.backendswing.CrearTableros;
import com.pablocompany.proyectono2lfp.backendswing.ModificarTabla;
import com.pablocompany.proyectono2lfp.excepciones.AnalizadorLexicoException;
import com.pablocompany.proyectono2lfp.excepciones.ErrorPuntualException;
import com.pablocompany.proyectono2lfp.excepciones.ErrorSintacticoException;
import com.pablocompany.proyectono2lfp.excepciones.ErroresRegistradosException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.text.BadLocationException;

/**
 *
 * @author pablo
 */
public class ReporteSintactico extends javax.swing.JDialog {

    /**
     * Creates new form MostrarReportes
     */
    private LectorEntradas gestionLecturas;


    //Gestiona el reporte de tokenizacion de lexemas
    private ModificarTabla mdTablitaTokenizacion;
    private CrearTableros crearTableroTokenizacion;

    //Atributo que permite pasar por parametro el lexema seleccionado para graficar sus transiciones
//    private Lexema lexemaSeleccionado;

    public ReporteSintactico(java.awt.Frame parent, boolean modal, LectorEntradas gestorLecturas) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);

        ColocarFondos pintarPanel = new ColocarFondos(this, this.panelPrincipal);
        ((JViewport) tableroVariables.getParent()).setBackground(new Color(0xF2D7B4));

        pintarPanel.pintarDialog("/com/pablocompany/proyectono1/recursosapp/images/overlay2.png");

        this.gestionLecturas = gestorLecturas;



        this.mdTablitaTokenizacion = new ModificarTabla(this.tableroVariables);
        this.crearTableroTokenizacion = new CrearTableros(this.tableroVariables);

      //  this.gestionLecturas.getGenerarReportes().reiniciarListas();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblReportes = new javax.swing.JLabel();
        panelErroes2 = new javax.swing.JPanel();
        btnReporteErrores = new javax.swing.JButton();
        lblConteoLexemas = new javax.swing.JLabel();
        lblConteoLexemas1 = new javax.swing.JLabel();
        jScrollTablero2 = new javax.swing.JScrollPane();
        tableroVariables = new javax.swing.JTable();
        btnReportarToken = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneErrores = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizacion de Reportes");
        setModal(true);

        lblReportes.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(83, 31, 11));
        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setText("Reportes Analizador Sintactico:");

        panelErroes2.setBackground(new java.awt.Color(111, 176, 209));
        panelErroes2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(50, 56, 68)));

        btnReporteErrores.setBackground(new java.awt.Color(0, 118, 0));
        btnReporteErrores.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnReporteErrores.setForeground(new java.awt.Color(229, 227, 227));
        btnReporteErrores.setText("Generar Reporte");
        btnReporteErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteErroresActionPerformed(evt);
            }
        });

        lblConteoLexemas.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        lblConteoLexemas.setForeground(new java.awt.Color(61, 29, 97));
        lblConteoLexemas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConteoLexemas.setText("Errores Sintacticos");

        lblConteoLexemas1.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        lblConteoLexemas1.setForeground(new java.awt.Color(61, 29, 97));
        lblConteoLexemas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConteoLexemas1.setText("Tabla de Variables");

        jScrollTablero2.setBackground(new java.awt.Color(242, 215, 180));
        jScrollTablero2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        tableroVariables.setBackground(new java.awt.Color(242, 215, 180));
        tableroVariables.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        tableroVariables.setForeground(new java.awt.Color(0, 0, 0));
        tableroVariables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableroVariables.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableroVariables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableroVariables.setGridColor(new java.awt.Color(0, 0, 0));
        tableroVariables.setRowSelectionAllowed(false);
        tableroVariables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableroVariablesMousePressed(evt);
            }
        });
        jScrollTablero2.setViewportView(tableroVariables);

        btnReportarToken.setBackground(new java.awt.Color(0, 118, 0));
        btnReportarToken.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnReportarToken.setForeground(new java.awt.Color(229, 227, 227));
        btnReportarToken.setText("Generar Reporte");
        btnReportarToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarTokenActionPerformed(evt);
            }
        });

        textPaneErrores.setBackground(new java.awt.Color(243, 216, 184));
        textPaneErrores.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        textPaneErrores.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(textPaneErrores);

        javax.swing.GroupLayout panelErroes2Layout = new javax.swing.GroupLayout(panelErroes2);
        panelErroes2.setLayout(panelErroes2Layout);
        panelErroes2Layout.setHorizontalGroup(
            panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErroes2Layout.createSequentialGroup()
                .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelErroes2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnReporteErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErroes2Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConteoLexemas, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErroes2Layout.createSequentialGroup()
                        .addComponent(btnReportarToken, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(panelErroes2Layout.createSequentialGroup()
                        .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollTablero2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConteoLexemas1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        panelErroes2Layout.setVerticalGroup(
            panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErroes2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConteoLexemas1)
                    .addComponent(lblConteoLexemas))
                .addGap(18, 18, 18)
                .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollTablero2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelErroes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportarToken, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelErroes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelErroes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteErroresActionPerformed
        //Muestra el reporte de listar los errores registrados
       try {

            if (this.gestionLecturas == null) {
                JOptionPane.showMessageDialog(this, "No hay texto registrado en el analizador\nEscribe algo para poderlo analizar", "Texto Vacio", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (this.gestionLecturas.getGenerarReportes() == null) {
                JOptionPane.showMessageDialog(this, "No hay texto registrado en el analizador", "Texto Vacio", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                //Boton manual que permite generar el reporte de conteo de lexemas
                this.gestionLecturas.getGestorSintactico().getReportes().generarReporteErrores(this.textPaneErrores);

            } catch (ErrorSintacticoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Inconveniente encontrado", JOptionPane.ERROR_MESSAGE);
            } catch (BadLocationException ex) { 
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de escritura", JOptionPane.ERROR_MESSAGE);
           } catch (ErroresRegistradosException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "No hay errores Sintacticos", JOptionPane.ERROR_MESSAGE);
           } 
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No se ha ejecutado el analisis sintactico\nPorfavor presiona el boton de \"Analisis Sintactico\"", "Texto Vacio", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnReporteErroresActionPerformed

    private void tableroVariablesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroVariablesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableroVariablesMousePressed

    private void btnReportarTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarTokenActionPerformed
        //Muestra el reporte en la tabla de conteo de lexemas en cantidad de veces que aparece
        try {

            if (this.gestionLecturas == null) {
                JOptionPane.showMessageDialog(this, "No hay texto registrado en el analizador\nEscribe algo para poderlo analizar", "Texto Vacio", JOptionPane.ERROR_MESSAGE);
                return;
            }

           /* if (this.gestionLecturas.getGenerarReportes() == null) {
                JOptionPane.showMessageDialog(this, "No hay texto registrado en el analizador", "Texto Vacio", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                //Boton manual que permite generar el reporte de conteo de lexemas
                this.gestionLecturas.getGenerarReportes().generarReporteTokenizacionLexemas(this.gestionLecturas.getLexerActual().getListadoSentencias(), this.mdTablitaTokenizacion, this.crearTableroTokenizacion);

            } catch (ErrorPuntualException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Inconveniente encontrado", JOptionPane.ERROR_MESSAGE);
            }*/

        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No hay texto registrado en el analizador\nEscribe algo para poderlo analizar", "Texto Vacio", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnReportarTokenActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportarToken;
    private javax.swing.JButton btnReporteErrores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollTablero2;
    private javax.swing.JLabel lblConteoLexemas;
    private javax.swing.JLabel lblConteoLexemas1;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JPanel panelErroes2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tableroVariables;
    private javax.swing.JTextPane textPaneErrores;
    // End of variables declaration//GEN-END:variables
}
